// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtHG-EfMHZOHKCxNqmxzABUYgop-VKz0Q',
    appId: '1:975773789579:web:537fa52c13b148ec1a938e',
    messagingSenderId: '975773789579',
    projectId: 'lockteclone',
    authDomain: 'lockteclone.firebaseapp.com',
    storageBucket: 'lockteclone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNfdgL-65LYrDhQN3J7dsYMw7oOg-XIpc',
    appId: '1:975773789579:android:36f6875d7101965c1a938e',
    messagingSenderId: '975773789579',
    projectId: 'lockteclone',
    storageBucket: 'lockteclone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtMI2k-nMgk0WPXtVp6RpEgbhS79XyTl4',
    appId: '1:975773789579:ios:130b4a82d4db85431a938e',
    messagingSenderId: '975773789579',
    projectId: 'lockteclone',
    storageBucket: 'lockteclone.appspot.com',
    androidClientId: '975773789579-stbq3o3gu85g6i8claqirgfrku9bscb1.apps.googleusercontent.com',
    iosClientId: '975773789579-mrhmubfpu7md9mvdhqh1n01egfa2uc88.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
