// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1tCjv10wBRFFpAjaBPTIGIEzWG8zwGyQ',
    appId: '1:1069158408953:web:b71dc526cbda801abaf828',
    messagingSenderId: '1069158408953',
    projectId: 'glogow-malopolski',
    authDomain: 'glogow-malopolski.firebaseapp.com',
    storageBucket: 'glogow-malopolski.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4xo_7TrgkxC_05KwbF81Xjo7q5jsmv0I',
    appId: '1:1069158408953:android:db2e859efacf2de9baf828',
    messagingSenderId: '1069158408953',
    projectId: 'glogow-malopolski',
    storageBucket: 'glogow-malopolski.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHFy2KKUHYKumKPCB0xIBed8giDVVBFQI',
    appId: '1:1069158408953:ios:de5bd9b40d296d9fbaf828',
    messagingSenderId: '1069158408953',
    projectId: 'glogow-malopolski',
    storageBucket: 'glogow-malopolski.appspot.com',
    iosClientId: '1069158408953-7ovjq2c6o5foesr41rivfhq7l4r91le0.apps.googleusercontent.com',
    iosBundleId: 'com.example.glogowMlp',
  );
}
